version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: golang
    versions:
    - 1.15.7.pre.alpine3.12
    - 1.15.8.pre.alpine3.12
    - 1.16.0.pre.alpine3.12
    - 1.16.1.pre.alpine3.12
    - 1.16.2.pre.alpine3.12
- package-ecosystem: pip
  directory: "/tests"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
