services: docker
language: python
python:
  - "3.6"

env:
  matrix:
    - ARCH=386
    - ARCH=amd64
    - ARCH=arm

install:
  - pip install --upgrade pip pipenv
  - pipenv sync --dev

script:
  - export VERSION="$(curl --silent https://api.github.com/repos/syncthing/syncthing/releases/latest | jq -r '.tag_name')"
  - ./build.sh $ARCH $VERSION

  - pipenv run pytest -v
  - docker run -d --name=syncthing-$ARCH --health-cmd="curl --fail http://127.0.0.1:8384/rest/system/ping || exit 1" --health-interval=5s --health-retries=3 robertbeal/syncthing:$ARCH
  - if [[ -z 'docker ps --filter="name=syncthing-$ARCH" --filter="health=healthy" -q' ]]; then exit 1; fi

deploy:
  provider: script
  script:
    echo "$DOCKER_PWD" | docker login -u "$DOCKER_USER" --password-stdin &&
    docker push robertbeal/syncthing:$ARCH &&
    docker push robertbeal/syncthing:$ARCH.$VERSION;
    docker manifest push "robertbeal/syncthing:$ARCH"

  on:
    branch: master
