services: docker
language: python
python:
  - "3.6"

env:
  matrix:
    - ARCH=i386 FILE=386
    - ARCH=amd64 FILE=amd64
    - ARCH=arm FILE=arm
    - ARCH=aarch64 FILE=arm64

install:
  - sudo apt-get install -y jq curl
  - pip install --upgrade pip pipenv
  - pipenv sync --dev

before_script:
  - ./build.sh $ARCH
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset

script:
  export VERSION=$(curl --silent "https://api.github.com/repos/syncthing/syncthing/releases/latest" | jq -r .tag_name)
  pipenv run pytest -v
  
  docker build \
    -t robertbeal/syncthing:$ARCH \
    -t robertbeal/syncthing:$ARCH.$VERSION \
    --build-arg=VERSION=$VERSION \
    --build-arg=VSC_REF=$(git rev-parse --short HEAD) \
    --build-arg=ARCH=$FILE \
    --file Dockerfile.$ARCH .
  
    docker run \
      -d \
      --name=syncthing-$ARCH \
      --health-cmd="curl --fail http://127.0.0.1:8384/rest/system/ping || exit 1" \
      --health-interval=5s \
      --health-retries=3 \
      robertbeal/syncthing:$ARCH

  if [[ -z 'docker ps --filter="name=syncthing-$ARCH" --filter="health=healthy" -q' ]]; then exit 1; fi

deploy:
  provider: script
  script:
    echo "$DOCKER_PWD" | docker login -u "$DOCKER_USER" --password-stdin &&
    docker push robertbeal/syncthing:$ARCH &&
    docker push robertbeal/syncthing:$ARCH.$VERSION;
  on:
    branch: master
