

name: build

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  build:
    runs-on: ubuntu-latest
    name: Architecture ${{ matrix.arch }} 

    strategy: 
      matrix:
        arch: ["386", "amd64", "arm"] 

    steps:
      - uses: actions/checkout@v2
      - name: python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: variables
        run: |
            curl --silent https://api.github.com/repos/syncthing/syncthing/releases/latest | jq -r '.tag_name' > version
      - name: build dependencies
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: build
        run: |
          docker buildx build \
            --tag robertbeal/syncthing:latest \
            --tag robertbeal/syncthing:$(cat version) \
            --platform linux/amd64,linux/arm/v7,linux/arm64
      - name: test dependencies
        run: |
            pip install --upgrade pip pipenv
            pipenv sync --dev
      - name: test
        run: |
          pipenv run pytest -v
          docker run -d --name=syncthing-${{ matrix.python-version }} --health-cmd="curl --fail http://127.0.0.1:8384/rest/system/ping || exit 1" --health-interval=5s --health-retries=3 robertbeal/syncthing:${{ matrix.python-version }}
          if [[ -z 'docker ps --filter="name=syncthing-${{ matrix.python-version }}" --filter="health=healthy" -q' ]]; then exit 1; fi
