

name: build

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  build:
    runs-on: ubuntu-latest
    name: Architecture ${{ matrix.arch }} 
    strategy: 
      matrix:
        arch: ["386", "amd64", "arm"] 

    steps:
      - uses: actions/checkout@v2
      - name: python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: dependencies
        run: |
            pip install --upgrade pip pipenv
            pipenv sync --dev
            export VERSION="$(curl --silent https://api.github.com/repos/syncthing/syncthing/releases/latest | jq -r '.tag_name')"
      - name: build
        run: |
          ./build.sh ${{ matrix.arch }} $VERSION
      - name: Test
        run: |
          pipenv run pytest -v
          docker run -d --name=syncthing-${{ matrix.python-version }} --health-cmd="curl --fail http://127.0.0.1:8384/rest/system/ping || exit 1" --health-interval=5s --health-retries=3 robertbeal/syncthing:${{ matrix.python-version }}
          if [[ -z 'docker ps --filter="name=syncthing-${{ matrix.python-version }}" --filter="health=healthy" -q' ]]; then exit 1; fi
